networks:
  presto_network:
    driver: bridge

volumes:
  pg_data:

services:
  presto:
    build: .
    container_name: bot
    networks:
      - presto_network
    env_file:
      - app.env
    depends_on:
      - postgres
  postgres:
    image: postgres:17.2-alpine
    container_name: postgres
    networks:
      - presto_network
    env_file:
      - pg.env
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data