services:
  go:
    build: .
    container_name: bot
    tty: true
    env_file:
      - .env
    environment:
      - PRESTO_ENVIRONMENT=development
      - BASE_DISCORD_CDN_URL=https://cdn.discordapp.com
      - BASE_DISCORD_API_URL=https://discord.com/api
      - DISCORD_API_VERSION=10
      - TESTING_GUILD_ID=${TESTING_GUILD_ID}
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    volumes:
      - .:/usr/presto
  postgresql:
    image: postgres:17.2
    container_name: postgresql
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
